### PR TITLE
Update for CUDA 12.4.0

### PR DESCRIPTION
**Pull request by adibbley**
xref: https://github.com/conda-forge/cuda-feedstock/issues/17

### CODE REVIEW

**Comment by adibbley** [comment]
@conda-forge-admin, please rerender

**Comment by jakirkham** [comment]
This did not build on `main` on either Azure or Travis CI. Have started two builds:

* https://app.travis-ci.com/github/conda-forge/cuda-nvprune-feedstock/builds/269313757
* https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=890692&view=results

**Comment by jakirkham** [comment]
It looks like packages are up. Though do see CI still running. It may have been accidentally started twice

**Comment by jakirkham** [comment]
Remaining CI job timed out in the queue so was marked as errored. Have restarted and it passed in short order (queue usage is much lower)

This should now be complete

**Pull request merged**
